### ISSUE TITLE
CRC error/corrupted graphics on 3 Count Bout

### ISSUE THREAD

**Issue by RealRelativeEase** [lioneltrs/goNCommand#10]
First off, huge thanks to everyone for creating and sharing these scripts!

The script for [3 Count Bout](https://github.com/RedundantCich/goNCommand/blob/main/Go3CB) released by RedundantCich builds a folder named 3countb.zip (CRC32: 4FC9DDAC), but FBNeo won't run the game and displays a CRC error instead. The game does boot in MAME Current, but the graphics are corrupted.

I've made no changes to the script itself, with the exception of the access and destination directories. I've also re-installed 3 Count Bount to rule out an issue with the game's files. Does the game work for anyone else?

**Comment by RedundantCich** [comment]
Hey, RealRelativeEase, I've just updated the file, and it should be working for 3countb :)

**Comment by RealRelativeEase** [comment]
It does, thank you very much! And thanks for working on these additional scripts! :)
