### ISSUE TITLE
Other titles from Amazon: Last Blade 2, Kof2003, Metal Slug 4

### ISSUE THREAD

**Issue by RedundantCich** [lioneltrs/goNCommand#2]
Did you try extracting them too? They seem to have similar files structure.

**Comment by RedundantCich** [comment]
OK, Last Blade 2 turned out to be pretty easy.
KoF2003 is also playing nicely. I seem to be getting wrong CRC on p1, but maybe that's nothing to worry about.

But Metal Slug 4 seems to be playing much rougher 🗡️ I'll spend some more time on it, and send you a PR (at least for LB2 and KoF2003)

**Comment by lioneltrs** [comment]
Hi RedundantCich,
1. I did not start working on Last Blade 2, as there was a Python script "lastblade2.py" posted on Good Old Games forum: https://www.gog.com/forum/general/rom_based_gog_games_compatible_with_third_party_emulators_thread?search=lastblade2.py

2. I started working on Metal Slug 4. However, it is not as simple as I expected. 263-m1.m1 CRC32 is OK, 263-v1.v1 and 263-v2.v2 match mslug4**a** CRC32. p1 CRC32 (c67f5c8d) is the one from mslug4**h** (with encrypted GFX) and p2 too (bc3ec89e). s1 CRC32 (1eaa05e0) is known as mslug4**a** hack according to /libretro-super/retroarch/media/libretrodb/metadat/fbneo-split/FinalBurn Neo (ClrMame Pro XML, Arcade only).dat  Feel free to investigate: so far, I am lost!
**Edit**: I added my work in progress script "goMS4" for Metal Slug 4. It does not work yet, but produces the files that I mentioned. Feel free to use it for your investigations.

3. KoF2003: I did not start working on it. For p1 with the wrong CRC32, did you try the same "trick" that I used for all the other games, that is: replace byte at address 0x115 (value = 02) by (value = 00)? It is the line almost at the end of all my scripts like:

printf '\x00' | dd of="$MY_OUT_ROM_DIR"/263-p1.p1 bs=1 seek=$((0x115)) count=1 conv=notrunc

I hope it helps.

Thanks for your interest, and keep up the good work!
Regards,
Lionel

**Comment by RedundantCich** [comment]
Hi Lionel,

awesome investigation (and great work on the whole repo btw! :))

1. I think it's cool to add it to your repo for completeness sake (I've set up a Pull Request).

2. Sounds crazy. I'll take a look if we can do something more with the files in these states.

3. It seems to be something different. I've tried exchanging that one byte and it didn't help. But maybe it's just a matter of some different tinkering. In general, I think I was overenthusiastic yesterday, because today all of the files are giving me wrong CRCs for kof2003 :D

**Comment by lioneltrs** [comment]
Thank you for your code: for LB2 it is my first "request", so I hope I did it right.

kof2003: I will check. However, as you wrote, it does not seem simple. Besides the sprites and the sound, I do not find known code for the two processors (Z80 and 68K) matching known CRC32. I summarize what matches known CRC32 below:

kf2k3ps2 // The King of Fighters 2003 - PlayStation 2 (Hack By EGCG)
dd6c6a85        271-v1c.v1 ==> yes
0e84f8c1        271-v2c.v2 ==> yes

e42fc226        271-c1c.c1 ==> yes
1b5e3b58        271-c2c.c2 ==> yes
d334fdd9        271-c3c.c3 ==> yes
0d457699        271-c4c.c4 ==> yes
8a91aae4        271-c5c.c5 ==> yes
9f8674b8        271-c6c.c6 ==> yes
efe714f8        271-c7c.c7 ==> **no**
c015cdb7        271-c8c.c8 ==> **no**

I used (command line, no decent script yet) :

```
./ss_unswizzle /home/lionel2/provi/amazon/kof2003/rom/c1.bin odd even
split -b 8388608 even even
split -b 8388608 odd odd

rm -r sprites
rm -r sound
mkdir -p sprites
mkdir -p sound
mv evenaa ./sprites/271-c2c.c2
mv evenab ./sprites/271-c4c.c4
mv evenac ./sprites/271-c6c.c6
mv evenad ./sprites/271-c8c.c8

mv oddaa ./sprites/271-c1c.c1
mv oddab ./sprites/271-c3c.c3
mv oddac ./sprites/271-c5c.c5
mv oddad ./sprites/271-c7c.c7

rm even odd


split -b 8388608 /home/lionel2/provi/amazon/kof2003/rom/v1.bin vv
mv vvaa ./sound/271-v1c.v1
mv vvab ./sound/271-v2c.v2
```

Feel free to adapt and test. v1.bin could also be the one from kof2003f or KOF2003d (source: mame2003-plus.xml)

Regards,
Lionel

**Comment by lioneltrs** [comment]
I reopen it, as neither MS4 nor KoF2003 are done yet.

**Comment by RedundantCich** [comment]
I doubt I will be able to solve it by my own, but it's fun to try :D

I'm also searching the internet for some more info.
This is something I found for mslug3:
https://i486-mods-jp.translate.goog/ichild/steam%e7%89%88%e3%83%a1%e3%82%bf%e3%83%ab%e3%82%b9%e3%83%a9%e3%83%83%e3%82%b03%e6%8c%91%e6%88%a6%e8%80%85%e6%b1%82%e3%82%80?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

It didn't work out in the end. But maybe there will be better results for mslug4. Though both seem to have simila problem with files from different rom versions.

**Comment by lioneltrs** [comment]
Yes, it is quite surprising.
